// Builds void-live-deploy/lib/stars.js: the 300 brightest stars with their names and constellations, and the constellation stick figures,
// from d3-celestial's data (Olaf Frohn, BSD-3-Clause; the stars are the Hipparcos catalog, J2000, magnitudes as catalogued).
//   node tools/build-stars.mjs <dir with stars.6.json starnames.json constellations.json constellations.lines.json>
// Fetch them first:  for f in stars.6 starnames constellations constellations.lines; do
//   curl -O https://raw.githubusercontent.com/ofrohn/d3-celestial/master/data/$f.json; done
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url)), dir = resolve(process.argv[2] || '.');
const read = (f) => JSON.parse(readFileSync(resolve(dir, f), 'utf8'));
const stars = read('stars.6.json').features, names = read('starnames.json'), cons = read('constellations.json').features, lines = read('constellations.lines.json').features;
const ra360 = (x) => ((x % 360) + 360) % 360, r2 = (x) => Math.round(x * 100) / 100, r1 = (x) => Math.round(x * 10) / 10;
const GREEK = { α: 'Alpha', β: 'Beta', γ: 'Gamma', δ: 'Delta', ε: 'Epsilon', ζ: 'Zeta', η: 'Eta', θ: 'Theta', ι: 'Iota', κ: 'Kappa', λ: 'Lambda', μ: 'Mu', ν: 'Nu', ξ: 'Xi', ο: 'Omicron', π: 'Pi', ρ: 'Rho', σ: 'Sigma', τ: 'Tau', υ: 'Upsilon', φ: 'Phi', χ: 'Chi', ψ: 'Psi', ω: 'Omega' };
const genitive = Object.fromEntries(cons.map((c) => [c.id, c.properties.gen]));

const pick = stars.filter((s) => Number.isFinite(s.properties.mag)).sort((a, b) => a.properties.mag - b.properties.mag).slice(0, 300);
const label = (s) => {
  const n = names[s.id] || {}; if (n.name) return n.name;
  const g = n.bayer && GREEK[n.bayer.replace(/\d+$/, '')];
  return g && genitive[n.c] ? g + ' ' + genitive[n.c] : n.flam && genitive[n.c] ? n.flam + ' ' + genitive[n.c] : 'HIP ' + s.id;
};
const rows = pick.map((s) => [r2(ra360(s.geometry.coordinates[0])), r2(s.geometry.coordinates[1]), s.properties.mag, label(s), (names[s.id] || {}).c || '']);
const used = new Set(rows.map((r) => r[4]));
const consNames = Object.fromEntries(cons.filter((c) => c.properties.name && c.id !== 'Ser' || c.id === 'Ser').map((c) => [c.id, c.properties.name]));
const figures = Object.fromEntries(lines.map((f) => [f.id, f.geometry.coordinates.map((poly) => poly.map(([x, y]) => [r1(ra360(x)), r1(y)]))]));
const out = `// GENERATED by tools/build-stars.mjs: do not edit. The ${rows.length} brightest stars (magnitude ${rows[0][2]} to ${rows[rows.length - 1][2]}) and the 88 constellation figures,
// from d3-celestial (Olaf Frohn, BSD-3-Clause, https://github.com/ofrohn/d3-celestial), whose stars are the Hipparcos catalog.
// STARS rows: [right ascension (J2000 degrees), declination (J2000 degrees), apparent magnitude, name, constellation abbreviation].
// FIGURES: constellation abbreviation -> polylines of [right ascension, declination] degrees (J2000), the usual stick figures.
export const STARS = ${JSON.stringify(rows)};
export const CONSTELLATIONS = ${JSON.stringify(consNames)};
export const FIGURES = ${JSON.stringify(figures)};
`;
writeFileSync(resolve(here, '..', 'void-live-deploy', 'lib', 'stars.js'), out);
console.log(`${rows.length} stars (${rows.filter((r) => !r[3].startsWith('HIP')).length} named, ${used.size} constellations), ${Object.keys(figures).length} figures, ${out.length} bytes`);
